All: Install: print error when scons is missing (#634)

diff --git a/Cassiopee/RigidMotion/install b/Cassiopee/RigidMotion/install
--- a/Cassiopee/RigidMotion/install
+++ b/Cassiopee/RigidMotion/install
@@ -49,7 +49,8 @@ if [ $PRODMODE -ge 0 ]; then
             $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
         fi
     else
-        python $sconsf install prefix="$INSTALLPATH" "$SCONSOPT"
+        echo "Error: scons not found."
+        exit 1
     fi
     [ $? != 0 ] && exit 1;
     #touch RigidMotion/rigidMotion.cpp
